services:
  discovery-service:
    build: ./discovery-service
    container_name: my-discovery-service
    ports:
      - '8761:8761'

    expose:
      - '8761'

    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost:8761/actuator/health" ]
      interval: 10s



  medecin-disponibilite-service:
    build: ./medecin-disponibilite
    container_name: my-medecin-dispo
    ports:
      - '8081:8081'

    expose:
      - '8081'
    depends_on:
       discovery-service:
         condition: service_healthy



  patient-service:
    build: ./patient-service
    container_name: my-patient-service
    ports:
      - '8083:8083'

    expose:
      - '8083'




  rendez-vous:
    build: ./rendez-vous
    container_name: my-rendezvous-service
    ports:
      - '8082:8082'

    expose:
      - '8082'



