spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path= /patients/**

        - id: r2
          uri: lb://RENDEZ-VOUS
          predicates:
            - Path= /api/rendezvous/**

        - id: r3
          uri: http://localhost:8081
          predicates:
            - Path= /api/disponibilites/**

        - id: r4
          uri: http://localhost:8081
          predicates:
            - Path= /api/praticiens/**

        - id: r5
          uri: http://localhost:8081
          predicates:
            - Path= /api/specialites/**